version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./configs:/app/configs
      - ./logs:/app/logs
      - ./models:/app/models
    environment:
      - DATABASE_URL=postgresql://vigia:vigia@db:5432/vigia
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=supersecretkey_change_this_in_production
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=vigia
      - POSTGRES_PASSWORD=vigia
      - POSTGRES_DB=vigia
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data: